repos:
-   repo: https://github.com/ambv/black
    rev: 23.11.0
    hooks:
    - id: black
      args: [--line-length=88, --safe]
      language: python
      language_version: python3
      files: ^(aoc_ranking/.*\.py|tests/.*\.py)
-   repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
    - id: isort
      language: python
      language_version: python3
      files: ^(aoc_ranking/.*\.py|tests/.*\.py)
      additional_dependencies:
        - toml

