repos:
-   repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
    - id: black
      args: [--line-length=88, --safe]
      language: python_venv
      language_version: python3
      files: ^(aoc_ranking/.*\.py|tests/.*\.py)
-   repo: https://github.com/timothycrosley/isort
    rev: 5.6.3
    hooks:
    - id: isort
      language: python_venv
      language_version: python3
      files: ^(aoc_ranking/.*\.py|tests/.*\.py)
      additional_dependencies:
        - toml

