
name: Update README ⭐
on:
  schedule:
    - cron: "51 */4 * * *"  # Every 4 hours
  workflow_dispatch:
jobs:
  runs-on: ubuntu-latest
    working_directory: ~/aoc-ranking
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}
      - run:
          name: Build
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -U pip setuptools wheel
            pip install poetry
            poetry install --no-ansi
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "poetry.lock" }}
          paths:
            - "venv"
      - run:
          name: Test
          command: |
            . venv/bin/activate
            poetry run pytest tests
